function q(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var r="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function t(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var u=t(this);function v(a,b){if(b)a:{var c=u;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&r(c,a,{configurable:!0,writable:!0,value:b})}}
v("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,f){this.ka=e;r(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.ka};var d=0;return b});
v("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=u[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&r(d.prototype,a,{configurable:!0,writable:!0,value:function(){return w(q(this))}})}return a});function w(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function x(a,b){a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}v("Array.prototype.keys",function(a){return a?a:function(){return x(this,function(b){return b})}});webABXre=/^(\d+)/;
webabx={sb:function(a){var b=webabx.i(a);if(b){var c=webABX.states[b];if(!webabx.m(b))return webabx.I(b);if(1>=c.b.length)alert(webABX.needTwoFilesABXError);else{if(0==c.D){if(!webabx.m(b))return webabx.I(b);webabx.aa(c);c.D=!0;webabx.H(b,c)}if(0==c.P){webabx.j();if(!webabx.m(b))return webabx.I(b);c.P=!0;c.C=webabx.Ma(c.b.length);c.B[c.B.length]=c.C;c.ia=c.C;var d=!0;document.getElementById(a).innerHTML=webABX.inABXText}else{if(c.S&&webabx.Y(c.b[c.C])){webabx.j();return}webabx.j();if(!webabx.m(b))return webabx.I(b);
d=!0}d&&(c.S=!0,webabx.N(document.getElementById(a)),webabx.Ba(b,c.b[c.C]))}}},tb:function(a){var b=webabx.i(a);if(b){var c=webABX.states[b];if(!webabx.m(b))return webabx.I(b);1>=c.b.length?alert(webABX.needTwoFilesShootoutError):(0==c.s&&(webabx.aa(c),c.s=!0,webabx.H(b,c)),0==c.F&&(c.F=!0,webabx.j(),webabx.pb(c),webabx.J(b,c),document.getElementById(a).innerHTML=webABX.inShootoutText),webabx.N(document.getElementById(a)))}},pb:function(a){a.a=Object.keys(a.b);for(var b=0;b<a.a.length;b++)a.a[b]=
parseInt(a.a[b]);for(b=a.a.length-1;0<b;b--){var c=Math.floor(Math.random()*(b+1)),d=a.a[b];a.a[b]=a.a[c];a.a[c]=d}},Ca:function(a){(a=webabx.i(a))&&webabx.ba(a,webABX.states[a])},La:function(a){if(a=webabx.o(a)){var b=webABX.states[a[0]];if("abx"==b.l)b.D?b.P?(webabx.j(),b.g++,b.c[b.c.length]=parseInt(a[1]),b.P=!1,b.B[b.B.length-1]==a[1]&&b.U++,webabx.H(a[0],b),document.getElementById(a[0]+"_xsb").innerHTML=webABX.nextABXText):alert(webABX.notInABXTestError):alert(webABX.notInABXSeriesError);else if("shootout"==
b.l)if(b.s)if(b.F){webabx.j();b.g++;b.F=!1;var c=a[1];0<b.a.length&&(c=b.a[c]);b.c[b.c.length]=parseInt(c);webabx.H(a[0],b);webabx.J(a[0],b);document.getElementById(a[0]+"_xsb").innerHTML=webABX.nextShootoutText}else alert(webABX.notInShootoutTestError);else alert(webABX.notInShootoutSeriesError)}},gb:function(a){var b=webabx.i(a);if(b&&(a=webABX.states[b],(b=document.getElementById(b+"_lpb"))&&a)){a.T=!a.T;for(var c=0;c<a.b.length;c++)a.b[c].loop=a.T;a.T?webabx.N(b):webabx.M(b)}},kb:function(a){if(a=
webabx.o(a)){var b=webABX.states[a[0]],c=a[1];0<b.a.length&&(c=b.a[c]);c=document.getElementById(webabx.ya(a,"pl",c));var d=document.getElementById(webabx.G(a,"psb"));if(c)if(!b.S&&webabx.Y(c))webabx.j();else{webabx.j();if(!webabx.m(a[0]))return webabx.I(a[0]);0>b.L?c.play():webabx.Ba(a[0],c);webabx.N(d)}}},Ba:function(a,b){b.currentTime/b.duration>webABX.atEndThreshold?b.currentTime=0:(a=document.getElementById(a+"_pp"),b.currentTime=a.value/a.max*b.duration);b.play()},m:function(a){var b=webABX.states[a].b;
if(!b)return!0;for(var c=0;c<b.length;c++)if(b[c])if(webABX.states[a].dataset.requireAllAudio){var d=b[c].buffered;if(1!=d.length||b[c].duration-(d.end(0)-d.start(0))>webABX.canPlayGapThreshold)return!1}else if(4!=b[c].readyState)return!1;return!0},I:function(a){var b=document.getElementById(a+"_asl");b.className=b.className.replace(webABX.audioLoadingErrorClass+"_disabled",webABX.audioLoadingErrorClass+"_enabled");setTimeout(function(c,d){return function(){webabx.lb(c,d)}}(a,b),3E3)},lb:function(a,
b){b.className=b.className.replace(webABX.audioLoadingErrorClass+"_enabled",webABX.audioLoadingErrorClass+"_disabled")},Ea:function(a){if(a=webabx.i(a)){var b=webABX.states[a];b.V=!b.V;webabx.H(a,b);"shootout"==b.l&&webabx.J(a,b)}},nb:function(a){if(a=webabx.i(a)){var b=webABX.states[a];webabx.ba(a,b);b.a=[];webabx.Da(a,b)}},Da:function(a,b){b.h=webabx.sa(a,b);b.K=webabx.Sa(b.h);webabx.ja(a,b)},Ia:function(a){if(a=webabx.i(a)){var b=webABX.states[a];webabx.ba(a,b);webabx.Na(a,b)}},vb:function(a){var b=
webabx.o(a);if(b){a=b[0];var c=webABX.states[b[0]];webabx.ba(a,c);b=b[1];var d=document.getElementById(a+"_plsw");document.getElementById(a+"_pl"+b+"w")&&d&&(0<c.a.length&&(b=c.a[b],c.a=webabx.rb(b,c.a)),webabx.mb(b,c.h,c.K),webabx.ja(a,c),0<c.a.length&&webabx.J(a,c))}},mb:function(a,b,c){b.splice(a,1);c.splice(a,1)},Sa:function(a){for(var b=[],c=0;c<a.length;c++)b[c]=1;return b},rb:function(a,b){for(var c=[],d=0;d<b.length;d++)b[d]<a?c[c.length]=b[d]:b[d]>a&&(c[c.length]=b[d]-1);return c},fb:function(a,
b){if(!(1>b||1>a.length)){for(var c=0;c<b;c++)a.unshift(c);for(c=0;c<b;c++)a[c]=c;for(c=b;c<a.length;c++)a[c]+=b}},J:function(a,b){if(b.F||b.s&&!b.V)for(var c=0;c<b.b.length;c++){var d=document.getElementById(a+"_fl"+c);var e=document.getElementById(a+"_nd"+c);var f=document.getElementById(a+"_grd"+c);d.innerHTML=webabx.R(c)+":";e.innerHTML=webABX.hiddenNameText;b.dataset.noVolumeControls||(f.style.display="none")}else for(c=0;c<b.b.length;c++){d=document.getElementById(a+"_fl"+c);e=document.getElementById(a+
"_nd"+c);f=document.getElementById(a+"_grd"+c);var g=document.getElementById(a+"_gr"+c);var h=document.getElementById(a+"_gri"+c);d.innerHTML=webabx.R(parseInt(c))+":";0<b.a.length?(e.innerHTML=webabx.O(a,b,parseInt(b.a[c])),d=document.getElementById(a+"_pl"+parseInt(b.a[c]))):(e.innerHTML=webabx.O(a,b,c),d=document.getElementById(a+"_pl"+c));b.dataset.noVolumeControls||(g.value=d.volume*g.max,h.style.opacity=d.volume,f.style.display="")}},O:function(a,b,c,d){if("fileset"===b.ga){if(void 0===d||null===
d){d=document.getElementById(a+"_nd"+c);if(void 0===d||null===d)return;d=d.getAttribute("data-xml-file-id")}if(void 0===b.f[d]||null===b.f[d])return;(a=b.f[d][1])||(a=b.f[d][0])}else(a=b.dataset["file"+(c+1)+"DisplayName"])||(a=b.dataset["file"+(c+1)+"Path"]);return a},ba:function(a,b){webabx.j();b.D?(webabx.aa(b),document.getElementById(a+"_xsb").innerHTML=webABX.startABXText):b.s&&(webabx.aa(b),document.getElementById(a+"_xsb").innerHTML=webABX.startShootoutText,webabx.J(a,b),webabx.M(document.getElementById(a+
"_xsb")));webabx.H(a,b)},H:function(a,b){var c=document.getElementById(a+"_rsb");c&&(b.V?(c.innerHTML=webABX.hideResultsText,webabx.N(c),c=document.getElementById(a+"_rd"),c.innerHTML=webabx.Wa(a,b),c.className=c.className.replace(webABX.appprefix+"results_hidden",webABX.appprefix+"results_visible")):(c.innerHTML=webABX.showResultsText,webabx.M(c),c=document.getElementById(a+"_rd"),c.innerHTML=webABX.resultsHiddenText,c.className=c.className.replace(webABX.appprefix+"results_visible",webABX.appprefix+
"results_hidden")),document.getElementById(a+"_tcv").innerHTML=b.g)},Wa:function(a,b){webabx.Ka(b);var c="";if(b.D)c+="<p>Number Correct: "+b.U+" of "+b.g+" ( "+(0<b.g?(b.U/b.g*100).toFixed(3):"0.000")+"%)</p><p>Confidence results are better than chance: "+(100*b.confidence).toFixed(3)+"%</p><p>Last trial was: "+(0<b.g?document.getElementById(a+"_nd"+b.ia).innerHTML:"(none yet)")+"</p>",c+=webabx.Va(b);else if(b.s){for(var d=Array(b.b.length+1).join("0").split("").map(parseFloat),e=0;e<b.c.length;e++)d[b.c[e]]+=
1;for(e=0;e<b.b.length;e++)c+="<p>"+d[e]+" time"+(1!=d[e]?"s - (":" - (")+(0==b.g?"0.000":(100*d[e]/b.g).toFixed(3))+"%) you chose "+webabx.O(a,b,e)+"</p>";c+=webabx.Xa(a,b)}else c=webABX.noResultsText;return c},Va:function(a){if(0>=a.c.length)return"";for(var b="<p>&nbsp;</p><p>Trial history (choice/actual):</p><p>",c=0;c<a.c.length;c++)b+=webabx.R(a.c[c])+"/"+webabx.R(a.B[c]),c+1<a.c.length&&(b+=" : ");return b+"</p>"},Xa:function(a,b){if(0>=b.c.length)return"";for(var c="<p>&nbsp;</p><p>Shootout history:</p>",
d=0;d<b.c.length;d++)c+="<p>#"+(d+1)+": "+webabx.O(a,b,b.c[d])+"</p>";return c},Ka:function(a){a.confidence=1-webabx.Pa(a.U,a.g,1/a.b.length)},Pa:function(a,b,c){for(var d=0;a<=b;a++)d+=webabx.Ja(a,b,c);return d},Ga:function(a){for(var b=1;1<a;)b*=a--;return b},ca:function(a){1>=a&&(a=1);if(12>a)return Math.log(webabx.Ga(Math.round(a)));var b=1/a,c=b*b,d=c*b,e=d*c;a=(a+.5)*Math.log(a)-a;a+=Math.log(2*Math.PI)/2;return a+(b/12-d/360)+(e/1260-e*c/1680)},Ha:function(a,b){return 0==b||b==a?0:b>a||0>b?
-1E38:webabx.ca(a)-webabx.ca(b)-webabx.ca(a-b)},Ja:function(a,b,c){return Math.exp(webabx.Ha(b,a)+a*Math.log(c)+(b-a)*Math.log(1-c))},Ma:function(a){return Math.floor(Math.random()*a)},j:function(){for(var a=Object.keys(webABX.states),b,c=0;c<a.length;c++){webABX.states[a[c]].S=!1;b=webABX.states[a[c]].b;for(var d=0;d<b.length;d++)b[d].pause();b=document.getElementById(a[c]+"_pp");webABX.states[a[c]].L=b.value}webabx.ra()},ra:function(){for(var a=document.getElementsByClassName(webABX.appprefix+"playstop_button"),
b=0;b<a.length;b++)webabx.M(a[b]);a=document.getElementsByClassName(webABX.appprefix+"abxstart_button");for(b=0;b<a.length;b++)webabx.M(a[b])},Za:function(a){a=webABX.states[a].b;for(var b=0;b<a.length;b++)if(webabx.Y(a[b]))return a[b]},Ya:function(a){return webABX.states[a].b[0]},Y:function(a){return!a.paused&&!a.ended&&0<a.currentTime},G:function(a,b){return a[0]+"_"+b+a[1]},ya:function(a,b,c){return a[0]+"_"+b+c},i:function(a){if((a=/^(.+)_.*/.exec(a))&&1<a.length&&a[1])return a[1]},o:function(a){a=
/^(.+)_[^0-9]+([0-9]+)[^0-9]*/.exec(a);if(void 0!==a&&null!==a&&0<a.length)return[a[1],a[2]]},N:function(a){a.className=a.className.replace(webABX.btnClass+"_disabled",webABX.btnClass+"_enabled")},M:function(a){a.className=a.className.replace(webABX.btnClass+"_enabled",webABX.btnClass+"_disabled")},R:function(a){return String.fromCharCode(65+a)},za:function(a){webabx.Oa(a,webABX.states[a])},ja:function(a,b){for(var c=document.getElementById(a+"_plsw");c.firstChild;)c.removeChild(c.firstChild);b.b=
[];b.v=void 0;for(var d=0;d<b.h.length;d++)webabx.pa(c,a,d,b.h.length,"compare"!=b.l,!0,b.f[b.h[d]][0],b.f[b.h[d]][1],b.h[d],b.f[b.h[d]][2],b.K[d])},Na:function(a,b){for(var c=webabx.sa(a,b),d=0;d<c.length;d++)-1!=b.h.indexOf(c[d])&&(c.splice(d,1),d--);c=c.sort();if(0<c.length){for(d=c.length-1;0<=d;d--)b.h.unshift(c[d]),b.K.unshift(1);webabx.fb(b.a,c.length);webabx.ja(a,b);0<b.a.length&&webabx.J(a,b)}},Oa:function(a,b){for(var c=[],d=document.getElementsByClassName(a+"_menu"),e=0,f=!0,g=0;g<d.length;g++)d[g].value&&
b.A[d[g].name]&&d[g].value!==webABX.anyOptionText.toLowerCase().trim()&&(f=!1,c[e++]=webabx.Ua(b.A[d[g].name][d[g].value]));f&&(c[0]=Object.keys(b.f));d=[];if(0>=c.length)d=[];else if(1==c.length)d=c[0];else for(e=c[0],g=0;g<e.length;g++){f=e[g];var h=!0;var m=1;b:for(;m<c.length;m++){var l=0;for(;l<c[m].length;l++)if(c[m][l]===f)continue b;h=!1;break b}h&&(d[d.length]=f)}d=d.sort();0<b.Z&&d.length>b.Z&&(d=d.splice(0,b.Z),alert(webABX.maxFilesErrorText));webabx.ub(a,b,d)},sa:function(a){a=document.getElementById(a+
"_mrms").firstChild;for(var b=[];a;)a.selected&&(b[b.length]=parseInt(a.getAttribute("value"))),a=a.nextSibling;return b},ub:function(a,b,c){for(var d=document.getElementById(a+"_mrms"),e;d.firstChild;)d.removeChild(d.firstChild);for(var f=0;f<c.length;f++)e=document.createElement("option"),e.id=a+"_opt"+f,e.className=webABX.appprefix+"menu_results_option",e.setAttribute("value",c[f]),e.setAttribute("selected",!0),e.appendChild(document.createTextNode(b.f[c[f]][1]?b.f[c[f]][1]:b.f[c[f]][0])),e.addEventListener("mouseover",
function(){webabx.ab(this.id,this.value)}),d.appendChild(e)},Ua:function(a){return[].concat.apply([],a)},Ab:function(a){for(var b=[],c,d=Object.keys(a),e=0;e<d.length;e++){c=a[d[e]];for(var f=0;f<c.length;f++)webabx.la(b,c[f])}return b},eb:function(a){if(a=webabx.o(a)){var b=document.getElementById(a[0]+"_pp"),c=document.getElementById(a[0]+"_lb"),d=document.getElementById(a[0]+"_rb"),e=document.getElementById(webabx.G(a,"pl"));if(e&&b){var f=e.currentTime/e.duration*b.max;if(c&&d){var g=(new Date).getTime();
300<g-webABX.lastBoundsSet&&(f<Number(c.value)?(e.currentTime=c.value/c.max*e.duration,f=c.value,webABX.lastBoundsSet=g):f>Number(d.value)&&(webabx.Y(e)&&!webABX.states[a[0]].T&&webabx.j(),e.currentTime=c.value/c.max*e.duration,f=c.value,webABX.lastBoundsSet=g))}b.value=f;webABX.states[a[0]].L=f;document.getElementById(a[0]+"_ppt").innerHTML=webabx.W(e.currentTime)}}},W:function(a){return Math.floor(a/60)+":"+("0"+(a-60*Math.floor(a/60)).toFixed(2)).slice(-5)},va:function(a){if(a=webabx.i(a)){var b=
document.getElementById(a+"_pp");if(b){var c=webabx.Za(a),d;c||(d=webabx.Ya(a));if(d||c)d=b.value/b.max*(c?c.duration:d.duration),c?(c.currentTime=b.value/b.max*c.duration,document.getElementById(a+"_ppt").innerHTML=webabx.W(c.currentTime)):(webABX.states[a].L=b.value,document.getElementById(a+"_ppt").innerHTML=webabx.W(d))}}},X:function(a,b){var c=webabx.i(a);if(c){a=document.getElementById(c+"_lb");var d=document.getElementById(c+"_rb");if(document.getElementById(c+"_pp")&&a&&d){c=Number(a.value);
var e=Number(d.value),f=Number(a.min),g=Number(d.max);b?e<=c&&(c+.1>g?(d.value=g,a.value=g-.1):d.value=c+.1):c>=e&&(e-.1<f?(a.value=f,d.value=f+.1):a.value=e-.1)}}},bb:function(a){if(a=webabx.o(a)){var b=document.getElementById(webabx.G(a,"pl"));b&&b.ended&&(webabx.ra(),b.currentTime=0,webABX.states[a[0]].L=0)}},ta:function(a){if(a=webabx.o(a)){var b=webABX.states[a[0]],c,d=document.getElementById(webabx.G(a,"gr")),e=document.getElementById(webabx.G(a,"gri"));0<b.a.length?(c=document.getElementById(webabx.ya(a,
"pl",parseInt(b.a[a[1]]))))&&d&&(c.volume=d.value/d.max,e.style.opacity=c.volume,b.K[parseInt(b.a[a[1]])]=c.volume):(c=document.getElementById(webabx.G(a,"pl")))&&d&&(c.volume=d.value/d.max,e.style.opacity=c.volume,b.K[a[1]]=c.volume)}},ha:function(a,b){var c=(new Date).getTime();b?webabx.m(a)?(document.getElementById(a+"_lpw").className=webABX.appprefix+"load_progress_wrap "+webABX.appprefix+"load_progress_wrap_disabled",webABX.states[a].v=void 0):(c-webABX.states[a].v>webABX.showLoadingProgressThreshold&&
(document.getElementById(a+"_lpw").className=webABX.appprefix+"load_progress_wrap "+webABX.appprefix+"load_progress_wrap_enabled"),c-webABX.states[a].v>1E3*webABX.chromeBugTimeout&&(window.yb&&window.zb||navigator.userAgent.match("CriOS"))&&(document.getElementById(a+"_lpt").innerHTML=webABX.loadProgressText+"<br/>"+webABX.chromeBugError),setTimeout(function(d){return function(){webabx.ha(d,!0)}}(a),webABX.playerCheckFreq)):c-webABX.states[a].xa>webABX.playerCheckFreq&&(webABX.states[a].xa=c,webabx.m(a)?
(document.getElementById(a+"_lpw").className=webABX.appprefix+"load_progress_wrap "+webABX.appprefix+"load_progress_wrap_disabled",webABX.states[a].v=void 0):c-webABX.states[a].v>webABX.showLoadingProgressThreshold&&(document.getElementById(a+"_lpw").className=webABX.appprefix+"load_progress_wrap "+webABX.appprefix+"load_progress_wrap_enabled"))},cb:function(a){if(a=webabx.o(a)){var b=webABX.states[a[0]];if(0!=Object.keys(b.u).length&&!b.s){var c=document.getElementById(a[0]+"_nd"+(0<b.a.length?b.a[a[1]]:
a[1]));void 0!==c&&null!==c&&(c=c.getAttribute("data-xml-file-id"),webabx.ua(a[0],b,c))}}},ab:function(a,b){if(a=webabx.o(a)){var c=webABX.states[a[0]];0!=Object.keys(c.u).length&&webabx.ua(a[0],c,b)}},ua:function(a,b,c){if(void 0!==b.f[c]&&null!==b.f[c]&&(c=b.f[c][3],void 0!==c&&null!==c)){for(var d,e,f=[],g=0;g<c.length;g++)d=c[g][0],e=b.u[d],void 0!==e&&null!==e&&null!==e[c[g][1]]&&webabx.na(a,d,e[c[g][1]])&&f.push(d);webabx.ma(a,b,f)}},$a:function(a,b,c){if(a=webabx.i(a)){var d=webABX.states[a];
0!=Object.keys(d.u).length&&void 0!==d.u[b]&&null!==d.u[b]&&webabx.na(a,b,d.u[b][c])&&webabx.ma(a,d,[b])}},na:function(a,b,c){if(void 0===c)return!1;a=document.getElementById(a+"_"+b+"_preview_image");if(void 0===a||null===a)return!1;for(var d=!1,e=0;e<a.childNodes.length;e++)if(b=a.childNodes[e].className,void 0!==b&&null!==b)if(b===webABX.appprefix+"preview_image")a.childNodes[e].style.backgroundImage="url('"+c[0]+"')",d=!0;else if(b===webABX.appprefix+"preview_image_caption"){for(;a.childNodes[e].firstChild;)a.childNodes[e].removeChild(a.childNodes[e].firstChild);
a.childNodes[e].appendChild(document.createTextNode(c[1]));d=!0}return d},ma:function(a,b,c){for(var d,e=0;e<b.$.length;e++){d=!1;for(var f=0;f<c.length;f++)d|=b.$[e]===c[f];if(!d&&(d=document.getElementById(a+"_"+b.$[e]+"_preview_image"),void 0!==d&&null!==d))for(var g=0;g<d.childNodes.length;g++)if(f=d.childNodes[g].className,void 0!==f&&null!==f)if(f===webABX.appprefix+"preview_image")d.childNodes[g].style.backgroundImage="initial";else if(f===webABX.appprefix+"preview_image_caption"){for(;d.childNodes[g].firstChild;)d.childNodes[g].removeChild(d.childNodes[g].firstChild);
d.childNodes[g].appendChild(document.createTextNode(""))}}},pa:function(a,b,c,d,e,f,g,h,m,l,n){void 0===n&&(n=1);h=webABX.states[b];var k=document.createElement("div");k.id=b+"_pl"+c+"w";k.className=webABX.appprefix+"player_wrap "+(6>d?webABX.appprefix+"player_wrap_evenrow":webABX.appprefix+(1==c%2?"player_wrap_oddrow":"player_wrap_evenrow"));a.appendChild(k);a=document.createElement("div");a.id=b+"_psb"+c;a.className=webABX.appprefix+"playstop_button "+webABX.appprefix+"button_disabled "+webABX.btnClass;
a.addEventListener("click",function(){webabx.kb(this.id)});k.appendChild(a);a=document.createElement("div");a.id=b+"_fl"+c;a.className=webABX.appprefix+"filelabel";a.appendChild(document.createTextNode(webabx.R(c)+":"));k.appendChild(a);a=document.createElement("div");a.id=b+"_nd"+c;a.className=webABX.appprefix+"filename";a.addEventListener("mouseover",function(){webabx.cb(this.id)});0<=m&&a.setAttribute("data-xml-file-id",m);a.appendChild(document.createTextNode(webabx.O(b,h,c,m)));k.appendChild(a);
f&&(f=document.createElement("div"),f.id=b+"_xb"+c,f.className=webABX.appprefix+"x_button "+webABX.appprefix+"button_disabled "+webABX.btnClass,f.addEventListener("click",function(){webabx.vb(this.id)}),k.appendChild(f));e&&(e=document.createElement("div"),e.id=b+"_cb"+c,e.className=webABX.appprefix+"choose_button "+webABX.appprefix+"button_disabled "+webABX.btnClass,e.appendChild(document.createTextNode("choose")),e.addEventListener("click",function(){webabx.La(this.id)}),k.appendChild(e));h.dataset.noVolumeControls||
(e=document.createElement("div"),e.id=b+"_grd"+c,e.className=webABX.appprefix+"gain_wrap",f=document.createElement("input"),f.id=b+"_gr"+c,f.className=webABX.appprefix+"gain_slider "+webABX.appprefix+"slider",f.type="range",f.min=0,f.max=1E4,f.step="any",f.value=n*f.max,f.addEventListener("input",function(){webabx.ta(this.id)},!0),f.addEventListener("change",function(){webabx.ta(this.id)},!0),e.appendChild(f),f=document.createElement("div"),f.id=b+"_gri"+c,f.className=webABX.appprefix+"gain_icon",
f.style.opacity=n,e.appendChild(f),k.appendChild(e));e=document.createElement("div");e.id=b+"_pl"+c+"d";e.className=webABX.appprefix+"audio_wrap";k.appendChild(e);k=document.createElement("audio");k.id=b+"_pl"+c;k.className=webABX.appprefix+"player";f=g?g:h.dataset["file"+(c+1)+"Path"];-1!==f.trim().toLowerCase().indexOf("wav",f.length-3)&&(k.canPlayType("audio/wav")||(g&&l?f=l:h.dataset["file"+(c+1)+"Path2"]&&(f=h.dataset["file"+(c+1)+"Path2"])));c=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.ka;
navigator.userAgent.match(/Version\/[\d\.]+.*Safari/)&&c||/constructor/i.test(window.HTMLElement)||"[object SafariRemoteNotification]"===(!window.safari||"undefined"!==typeof safari&&safari.Bb).toString()?k.src=f:webabx.ob(k,f);k.preload="auto";k.addEventListener("timeupdate",function(){webabx.eb(this.id)},!0);k.addEventListener("pause",function(){webabx.bb(this.id)},!0);k.addEventListener("progress",function(p){return function(){webabx.ha(p)}}(b));k.loop=!0;k.volume=n;e.appendChild(k);h.v||(h.v=
(new Date).getTime(),setTimeout(function(p){return function(){webabx.ha(p,!0)}}(b),webABX.showLoadingProgressThreshold+11));h.b[h.b.length]=k},ob:function(a,b){var c=new XMLHttpRequest;c.open("GET",b);c.onreadystatechange=function(){4==this.readyState&&200==this.status&&(a.src=window.URL.createObjectURL(c.response))};c.responseType="blob";c.send()},fa:function(a,b){var c=document.createElement("div");c.id=a.id+"_pr";c.className=webABX.appprefix+"playranges_wrap";a.appendChild(c);var d=document.createElement("div");
d.id=a.id+"_ppd";d.className=webABX.appprefix+"play_position_slider_wrap "+webABX.appprefix+"ranges_slider_wrap";var e=document.createElement("div");e.id=a.id+"_ppld";e.className=webABX.appprefix+"play_position_loop_div "+webABX.appprefix+"ranges_column_div";var f=document.createElement("div");f.id=a.id+"_ppt";f.className=webABX.appprefix+"play_position_text";f.appendChild(document.createTextNode(webabx.W(0)));var g=document.createElement("div");g.id=a.id+"_lpb";g.className=webABX.appprefix+"loop_button "+
webABX.appprefix+"button_enabled "+webABX.btnClass;g.addEventListener("click",function(){webabx.gb(this.id)});e.appendChild(g);e.appendChild(f);f=document.createElement("input");f.id=a.id+"_pp";f.className=webABX.appprefix+"play_position_slider "+webABX.appprefix+"range_slider "+webABX.appprefix+"slider";f.type="range";f.min=0;f.max=1E4;f.step="any";f.value=0;f.addEventListener("input",function(){webabx.va(this.id)},!0);f.addEventListener("change",function(){webabx.va(this.id)},!0);d.appendChild(e);
d.appendChild(f);c.appendChild(d);if(b){b=document.createElement("div");b.id=a.id+"_lbd";b.className=webABX.appprefix+"left_bounds_slider_wrap "+webABX.appprefix+"ranges_slider_wrap";d=document.createElement("div");d.id=a.id+"_lbtd";d.className=webABX.appprefix+"play_position_left_bounds_text_div "+webABX.appprefix+"ranges_column_div";d.appendChild(document.createTextNode(webABX.leftBoundsText));e=document.createElement("input");e.id=a.id+"_lb";e.className=webABX.appprefix+"left_bounds_slider "+webABX.appprefix+
"range_slider "+webABX.appprefix+"slider";e.type="range";e.min=0;e.max=1E4;e.step="any";e.value=0;e.addEventListener("input",function(){webabx.X(this.id,!0)},!0);e.addEventListener("change",function(){webabx.X(this.id,!0)},!0);f=document.createElement("div");f.id=a.id+"_rbd";f.className=webABX.appprefix+"right_bounds_slider_wrap "+webABX.appprefix+"ranges_slider_wrap";g=document.createElement("div");g.id=a.id+"_lbtd";g.className=webABX.appprefix+"play_position_right_bounds_text_div "+webABX.appprefix+
"ranges_column_div";g.appendChild(document.createTextNode(webABX.rightBoundsText));var h=document.createElement("input");h.id=a.id+"_rb";h.className=webABX.appprefix+"right_bounds_slider "+webABX.appprefix+"range_slider "+webABX.appprefix+"slider";h.type="range";h.min=0;h.max=1E4;h.step="any";h.value=1E4;h.addEventListener("input",function(){webabx.X(this.id,!1)},!0);h.addEventListener("change",function(){webabx.X(this.id,!1)},!0);b.appendChild(d);b.appendChild(e);f.appendChild(g);f.appendChild(h);
c.appendChild(b);c.appendChild(f)}},xb:function(a){var b=webABX.states[a],c=webABX.fxmls[a];if(c&&4===c.readyState&&200===c.status)if(c.responseXML){for(var d=c.responseXML.getElementsByTagName("menu"),e=document.getElementById(a+"_msw"),f,g,h,m,l=0;l<d.length;l++)f=document.createElement("div"),f.id=a+"_mw"+l,f.className=webABX.appprefix+"menu_wrap",g=document.createElement("div"),g.id=a+"_mtd"+l,g.className=webABX.appprefix+"menu_title",g.innerHTML=d[l].textContent,h=document.createElement("select"),
h.name=d[l].attributes.id.value.toLowerCase().trim(),b.$.push(h.name),h.id=a+"_menu_"+h.name,h.className=webABX.appprefix+"tagselect "+a+"_menu",h.onchange=function(y){return function(){webabx.za(y)}}(a),m=document.createElement("option"),m.className=webABX.appprefix+"menuoption",m.selected=!0,m.value=webABX.anyOptionText,m.innerHTML=webABX.anyOptionText,h.appendChild(m),f.appendChild(g),f.appendChild(h),e.appendChild(f),d[l].attributes["default"]&&(b.Aa[d[l].getAttribute("id")]=d[l].attributes["default"].value.toLowerCase().trim());
e=c.responseXML.getElementsByTagName("file");for(l=0;l<e.length;l++){f=e[l].attributes;h=g=m=void 0;var n=[];for(d=0;d<f.length;d++)if("name"===f[d].name)m=f[d].value;else if("path"===f[d].name)g=f[d].value;else if("path2"===f[d].name)h=f[d].value;else{var k=f[d].name.toLowerCase().trim();var p=f[d].value;document.getElementById(a+"_menu_"+k)&&webabx.ib(k,document.getElementById(a+"_menu_"+k),p,b.Aa,a);p=p.toLowerCase().trim();n[n.length]=[k,p]}if(g){for(d=0;d<n.length;d++)k=n[d][0],p=n[d][1],b.A[k]||
(b.A[k]={}),b.A[k][p]||(b.A[k][p]=[]),webabx.la(b.A[k][p],l);m||(m=g);b.f[l]=[g,m,h,n]}}c=c.responseXML.getElementsByTagName("menuimages");for(l=0;l<c.length;l++)if(d=c[l],e=[],null!==d&&(f=d.getAttribute("id"),g=d.children,0!=g.length)){for(d=0;d<g.length;d++)h=g[d].getAttribute("key"),m=g[d].getAttribute("value"),k=g[d].textContent,void 0!==m&&null!==m&&(e[h.toLowerCase().trim()]=[m,k]);b.u[f]=e}webabx.za(a);void 0!==b.dataset.noInitialBuffering&&!1!==b.dataset.noInitialBuffering&&"false"!==b.dataset.noInitialBuffering||
webabx.Da(a,b)}else webabx.Fa(webABX.genericXMLError+" Error 1")},la:function(a,b){-1<a.indexOf(b)||(a[a.length]=b)},ib:function(a,b,c,d,e){for(var f=0,g=0;g<b.childNodes.length;g++){if(b.childNodes[g].value===c.toLowerCase().trim())return;if(webabx.qb(b.childNodes[g].value,c.toLowerCase().trim()))break;f++}g=document.createElement("option");g.className=webABX.appprefix+"menuoption";g.value=c.toLowerCase().trim();g.setAttribute("data-menu-id",a);g.innerHTML=c;g.id=e+"_menuopt";g.addEventListener("mouseover",
function(){webabx.$a(this.id,this.getAttribute("data-menu-id"),this.value)});f==b.childNodes.length?b.appendChild(g):b.insertBefore(g,b.childNodes[f]);g.value===d[a]&&(g.selected=!0)},qb:function(a,b){var c=webABXre.exec(a);if(null===c)return a>b;a=webABXre.exec(b);return null===a?!1:parseInt(c[1])>parseInt(a[1])},wb:function(a){webabx.Fa(a,webABX.genericXMLError+" Error 3")},Fa:function(a,b){document.getElementById(a+"_msw").innerHTML="<B>"+b+"</B>"},ea:function(a,b,c){var d=0;a.className+=" "+webABX.appprefix+
b.l;var e=document.createElement("div");e.id=a.id+"_asl";e.className=webABX.audioLoadingErrorClass+" "+webABX.audioLoadingErrorClass+"_disabled";e.appendChild(document.createTextNode(webABX.loadingAudioError));a.appendChild(e);e=document.createElement("div");e.id=a.id+"_lpw";e.className=webABX.appprefix+"load_progress_wrap "+webABX.appprefix+"load_progress_wrap_disabled";var f=document.createElement("div");f.id=a.id+"_lpt";f.className=webABX.appprefix+"load_progress_text";f.appendChild(document.createTextNode(webABX.loadProgressText));
var g=document.createElement("div");g.id=a.id+"_lpi";g.className=webABX.appprefix+"load_progress_icon";e.appendChild(f);e.appendChild(g);a.appendChild(e);void 0!=b.dataset.comparisonTitle&&null!=b.dataset.comparisonTitle&&""!==b.dataset.comparisonTitle.trim()&&(e=document.createElement("div"),e.id=a.id+"_ctl",e.className=webABX.appprefix+"comparison_title",e.appendChild(document.createTextNode(b.dataset.comparisonTitle)),a.appendChild(e));b.dataset.maxFileResults&&(b.Z=parseInt(b.dataset.maxFileResults));
b.dataset.xmlFileSet&&(e=document.createElement("div"),e.id=a.id+"_msw",e.className=webABX.appprefix+"menus_wrap",a.appendChild(e),e=document.createElement("div"),e.id=a.id+"_mrsw",e.className=webABX.appprefix+"menu_results_wrap",f=document.createElement("div"),f.id=a.id+"_mrswt",f.className=webABX.appprefix+"menu_results_title",f.appendChild(document.createTextNode(webABX.menuResultsTitle)),e.appendChild(f),f=document.createElement("select"),f.id=c+"_mrms",f.className=webABX.appprefix+"menu_results_multichoice",
f.setAttribute("multiple","multiple"),e.appendChild(f),a.appendChild(e));b.dataset.xmlFileSet&&(e=document.createElement("div"),e.id=c+"_fbd",e.className=webABX.appprefix+"filter_buttons",f=document.createElement("div"),f.id=c+"_adb",f.className=webABX.appprefix+"add_button "+webABX.appprefix+"button_disabled "+webABX.btnClass,f.appendChild(document.createTextNode(webABX.addButtonText)),f.addEventListener("click",function(){webabx.Ia(this.id)}),g=document.createElement("div"),g.id=c+"_sb",g.className=
webABX.appprefix+"search_button "+webABX.appprefix+"button_disabled "+webABX.btnClass,g.appendChild(document.createTextNode(webABX.searchButtonText)),g.addEventListener("click",function(){webabx.nb(this.id)}),e.appendChild(f),e.appendChild(g),a.appendChild(e));e=document.createElement("div");e.id=a.id+"_plsw";e.className=webABX.appprefix+"players_wrap";a.appendChild(e);if(b.dataset.xmlFileSet)b.ga="fileset",d=new XMLHttpRequest,a=b.dataset.xmlFileSet,b.dataset.appendTimestamp&&(a=-1!=a.indexOf("?")?
a+"&ts=":a+"?ts=",a+=(new Date).getTime()),d.open("GET",a,!0),b.dataset.noCache&&(d.setRequestHeader("If-Modified-Since","Sat, 1 Jan 2005 00:00:00 GMT"),d.setRequestHeader("Pragma","no-cache"),d.setRequestHeader("Cache-Control","no-cache")),d.onload=function(h){return function(){webabx.xb(h)}}(c),d.onerror=function(h){return function(){webabx.wb(h)}}(c),webABX.fxmls[c]=d,d.send();else{b.ga="dataset";a=Object.keys(b.dataset);for(f=0;f<a.length;f++)0===a[f].lastIndexOf("file",0)&&-1!=a[f].indexOf("Path",
a[f].length-4)&&d++;for(f=0;f<d;f++)webabx.pa(e,c,f,d,"compare"!=b.l,!1)}},Ra:function(a){var b=webABX.states[a.id];b.l="compare";webabx.ea(a,b,a.id);webabx.fa(a,"true"!==b.dataset.noBounds);webabx.da(a,a.id)},Qa:function(a){var b=webABX.states[a.id];b.l="abx";webabx.ea(a,b,a.id);webabx.fa(a,"true"!==b.dataset.noBounds);b=document.createElement("div");b.id=a.id+"_cw";b.className=webABX.appprefix+"control_wrap";var c=document.createElement("div");c.id=a.id+"_xsb";c.className=webABX.appprefix+"abxstart_button "+
webABX.appprefix+"button_disabled "+webABX.btnClass;c.appendChild(document.createTextNode(webABX.startABXText));c.addEventListener("click",function(){webabx.sb(this.id)});var d=document.createElement("div");d.id=a.id+"_rsb";d.className=webABX.appprefix+"results_button "+webABX.appprefix+"button_disabled "+webABX.btnClass;d.appendChild(document.createTextNode(webABX.showResultsText));d.addEventListener("click",function(){webabx.Ea(this.id)});var e=document.createElement("div");e.id=a.id+"_rstb";e.className=
webABX.appprefix+"reset_button "+webABX.appprefix+"button_disabled "+webABX.btnClass;e.appendChild(document.createTextNode(webABX.resetText));e.addEventListener("click",function(){webabx.Ca(this.id)});a.appendChild(b);b.appendChild(c);b.appendChild(d);b.appendChild(e);webabx.qa(a,webABX.initialResultsABXText);webabx.da(a,a.id)},Ta:function(a){var b=webABX.states[a.id];b.l="shootout";webabx.ea(a,b,a.id);webabx.fa(a,"true"!==b.dataset.noBounds);b=document.createElement("div");b.id=a.id+"_cw";b.className=
webABX.appprefix+"control_wrap";var c=document.createElement("div");c.id=a.id+"_xsb";c.className=webABX.appprefix+"shootoutstart_button "+webABX.appprefix+"button_disabled "+webABX.btnClass;c.appendChild(document.createTextNode(webABX.startShootoutText));c.addEventListener("click",function(){webabx.tb(this.id)});var d=document.createElement("div");d.id=a.id+"_rsb";d.className=webABX.appprefix+"results_button "+webABX.appprefix+"button_disabled "+webABX.btnClass;d.appendChild(document.createTextNode(webABX.showResultsText));
d.addEventListener("click",function(){webabx.Ea(this.id)});var e=document.createElement("div");e.id=a.id+"_rstb";e.className=webABX.appprefix+"reset_button "+webABX.appprefix+"button_disabled "+webABX.btnClass;e.appendChild(document.createTextNode(webABX.resetText));e.addEventListener("click",function(){webabx.Ca(this.id)});a.appendChild(b);b.appendChild(c);b.appendChild(d);b.appendChild(e);webabx.qa(a,webABX.initialResultsShootoutText);webabx.da(a,a.id)},qa:function(a,b){var c=document.createElement("div");
c.id=a.id+"_rw";c.className=webABX.appprefix+"results_wrap";var d=document.createElement("div");d.id=a.id+"_tcw";d.className=webABX.appprefix+"tests_complete_wrap";var e=document.createElement("div");e.id=a.id+"_tcd";e.className=webABX.appprefix+"test_complete_text";e.appendChild(document.createTextNode("# Tests Completed:"));var f=document.createElement("div");f.id=a.id+"_tcv";f.className=webABX.appprefix+"test_complete_value";f.appendChild(document.createTextNode("0"));d.appendChild(e);d.appendChild(f);
e=document.createElement("div");e.id=a.id+"_rd";e.className=webABX.appprefix+"results webabx_results_hidden";e.appendChild(document.createTextNode(b));c.appendChild(d);c.appendChild(e);a.appendChild(c)},da:function(a,b){var c=document.createElement("div");c.id=b+"_atw";c.className=webABX.appprefix+"attribution_wrap dont_hide_this_unless_a_paying_customer_thanks";var d=document.createElement("div");d.id=b+"_ati";d.className=webABX.appprefix+"attribution_icon dont_hide_this_unless_a_paying_customer_thanks";
var e=document.createElement("div");e.id=b+"_att";e.className=webABX.appprefix+"attribution dont_hide_this_unless_a_paying_customer_thanks";e.innerHTML=webABX.attributionText;c.appendChild(d);c.appendChild(e);a.appendChild(c)},wa:function(){var a=document.getElementsByClassName("webabx_"+webABX.versiontag);webabx.oa(document.getElementsByClassName("webabx"));webabx.oa(a)},oa:function(a){if(a){for(var b=0;b<a.length;b++)webABX.states[a[b].id]=webabx.hb(a[b]);var c;for(b=0;b<a.length;b++)if(c=a[b])"compare"==
a[b].dataset.comparisonType?webabx.Ra(c,b):"abx"==a[b].dataset.comparisonType?webabx.Qa(c,b):"shootout"==a[b].dataset.comparisonType?webabx.Ta(c,b):a[b].innerHTML="Unrecognized comparison type: "+c.dataset.comparisonType}},hb:function(a){return{l:"unset",dataset:a.dataset,ga:"unset",A:{},f:[],h:[],K:[],u:[],Z:-1,$:[],Aa:{},P:!1,D:!1,F:!1,s:!1,g:0,U:0,confidence:0,C:-1,ia:-1,c:[],B:[],b:[],a:[],L:-1,T:!0,V:!1,S:!1,xa:0}},aa:function(a){a.P=!1;a.D=!1;a.F=!1;a.s=!1;a.g=0;a.U=0;a.confidence=0;a.C=-1;
a.ia=-1;a.c=[];a.B=[];a.V=!1;a.S=!1}};webABX={versionstring:"1.63",versiontag:"1p63",states:{},fxmls:{},appprefix:"webabx_",appname:"Lacinato WebABX/Shootouter",appweblink:"http://lacinato.com/webabx"};webABX.btnClass=webABX.appprefix+"button";webABX.atEndThreshold=.995;webABX.canPlayGapThreshold=1;webABX.playerCheckFreq=500;webABX.showLoadingProgressThreshold=1E3;webABX.menuResultsTitle="Filter results (select the files that interest you):";webABX.lastBoundsSet=new Date;webABX.leftBoundsText="start time";
webABX.rightBoundsText="end time";webABX.startABXText="Start ABX";webABX.startShootoutText="Start Shootout";webABX.inABXText="Play X";webABX.inShootoutText="(in shootout)";webABX.hiddenLabelText="-";webABX.hiddenNameText="(shuffled)";webABX.nextShootoutText="Next Shootout";webABX.nextABXText="Next X";webABX.showResultsText="Show Results";webABX.hideResultsText="Hide Results";webABX.resultsHiddenText="(results hidden)";webABX.noResultsText="(no results to show)";webABX.resetText="Reset";
webABX.addButtonText="Add";webABX.searchButtonText="Only These";webABX.notInABXSeriesError='You must start an ABX test before you can choose a file. Click "'+webABX.startABXText+'".';webABX.needTwoFilesABXError="You need at least two files ready to play before starting an ABX test.";webABX.needTwoFilesShootoutError="You need at least two files ready to play before starting a shootout.";webABX.notInABXTestError='You must click "'+webABX.nextABXText+'" before you can choose the next file.';
webABX.notInShootoutSeriesError='You must start a shootout before you can choose a file. Click "'+webABX.startShootoutText+'".';webABX.notInShootoutTestError='You must click "'+webABX.nextShootoutText+'" before you can choose the next file.';webABX.initialResultsABXText='Click "'+webABX.startABXText+'" to start test.';webABX.initialResultsShootoutText='Click "'+webABX.startShootoutText+'" to start shootout.';webABX.genericXMLError="There was a problem loading the audio files...";
webABX.maxFilesErrorText="Sorry -- some files will not be compared because too many were returned. Try narrowing your search options with the menus.";webABX.anyOptionText="(any)";webABX.attributionText='Audio comparison by <a href="'+webABX.appweblink+'">'+webABX.appname+"</a>";webABX.loadProgressText="Buffering audio...";webABX.loadingAudioError="Sorry -- not enough audio has downloaded yet. Please try again soon.";webABX.audioLoadingErrorClass=webABX.appprefix+"audio_loading_error";
webABX.chromeBugError="Note that a bug in Chrome causes failure when loading more than six files simultaneously. If buffering never stops, try reloading the page, or try another browser.";webABX.chromeBugTimeout=10;webabx.jb=window.onload;window.onload="function"!=typeof window.onload?webabx.wa:function(){webabx.jb();webabx.wa()};
